/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://rmees7oeynhutocfo5lm6dwj6u.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": process.env.AS_APIKEY,
    "aws_cognito_identity_pool_id": "us-east-2:62472a3a-5199-4fd1-88de-0f44742d1bb8",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_MuNfKaDZF",
    "aws_user_pools_web_client_id": "5mdv2hl9olph5inlrn21ao6nsj",
    "oauth": {},
    "aws_user_files_s3_bucket": "hhaabucket150930-staging",
    "aws_user_files_s3_bucket_region": "us-east-2"
    
};


export default awsmobile;
